#!/usr/bin/env bash

# x64 build
dotnet publish SpeedTest.Cli/SpeedTest.Cli.csproj \
  -c Release -r linux-x64 \
  --self-contained true \
  /p:PublishAot=true \
  -o publish/linux-x64

# arm64 build (must use clang)
CC=clang CXX=clang++ \
dotnet publish SpeedTest.Cli/SpeedTest.Cli.csproj \
  -c Release -r linux-arm64 \
  --self-contained true \
  /p:PublishAot=true \
  -o publish/linux-arm64
