[Service]
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW
NoNewPrivileges=false
PrivateMounts=false
SupplementaryGroups=systemd-journal
Environment=HOME=/var/lib/telegraf
